language: node_js

node_js:
  - "8"

sudo: false

branches:
   only:
   - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

deploy:
  provider: npm
  email: "jared.farago@gmail.com"
  api_key: "20189b3a-58c8-41fb-8c20-65864395a046"

script:
  - yarn && yarn test
